### ISSUE TITLE
About the dataset issues

### ISSUE THREAD

**Issue by YangYuqi317** [thoranna/learning_to_taste#1]
Hello! I am interested in this work, so I am thinking about running your code with WineSensed dataset, could you provide the data/ files in your code? Thanks！

**Comment by thoranna** [comment]
Hi! 

The data in my code is the wines from the WineSensed dataset that have experiment id's (those we have human flavor annotations on). 

If it's too tricky to filter I can upload and share the folder I used here on Google Drive

**Comment by YangYuqi317** [comment]
Thank you for your response! I have downloaded the WineSensed dataset, but there are still some problems, could you please upload the relevant folder? Thanks！

**Comment by thoranna** [comment]
No problem! Could you share your email?

**Comment by YangYuqi317** [comment]
Thanks! My email is yangyuqi@bupt.edu.cn

**Comment by YangYuqi317** [comment]
Thanks！My email is yangyuqi0317@gmail.com

**Comment by thoranna** [comment]
Shared with you!

**Comment by thoranna** [comment]
If others struggle with the same issue you can comment your email here and I will share the folder but this is a temporary solution as I will make the documentation on how to use our WineSensed dataset with the code more clear

**Comment by KangKanng** [comment]
hello, i am very interested in your work, can you send me your data to reproduce your work, my email is yuanchizhu1020@gmail.com, really appreciate it!@thoranna

**Comment by thorannabender** [comment]
Hi, our dataset is publicly available at https://data.dtu.dk/articles/dataset/WineSensed_Learning_to_Taste_A_Multimodal_Wine_Dataset/23376560 and on HuggingFace https://huggingface.co/datasets/Dakhoo/L2T-NeurIPS-2023.

I have put the data that is used in this repo specifically in https://drive.google.com/drive/folders/19UkmL2-8uHx6w8BRmNwF_ysvPpYYyzKW?usp=sharing for easier reuse of the code, feel free to access the dataset in any of those places.

**Comment by scotsman44** [comment]
Hello @thoranna ! I am a student looking at doing an extension of your very interesting work on WineSense and I have a question on scraping permissions for Vivino; I can see that you reference the website in your paper, but wondered if the team sought explicit permission to use the data (unclear if it was scraped vs provided directly by the platform). My email is jamesharrisscott@gmail.com, and any guidance much appreciated.
